version: '3'

#
# run with
# docker compose up --exit-code-from tests --build --abort-on-container-exit && docker compose logs tests && docker compose down
#
services:
  aswh:
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: on-failure
    environment:
      - NODE_ENV=development
      - LOG_level__default=error
    volumes:
      - ./aswh-etc:/usr/src/app/etc
    depends_on:
      - mongo
      - redis
      - postgres

  tests:
    build:
      context: ./
      dockerfile: ./Dockerfile

#    image: node:14.15.1-alpine
#    command: tail -f /dev/null
#    volumes:
#      - ./:/app

    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.2-bionic
    command: --logpath /dev/null
    restart: on-failure

  redis:
    image: redis:alpine
    restart: on-failure

  postgres:
    image: postgres:16.3
    restart: on-failure
    environment:
      POSTGRES_USER:     pg
      POSTGRES_PASSWORD: pg

networks:
  default:

